CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(64)     NOT NULL,
    name           VARCHAR(255)    NOT NULL,
    price          DECIMAL(15, 2) NOT NULL,
    stock_quantity INTEGER         NOT NULL,
    active         BOOLEAN         NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku)
);
