-- Create new employees table with additional employee fields
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK(role IN ('ADMIN', 'HR', 'MANAGER', 'EMPLOYEE')),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    refresh_token VARCHAR(64),
    refresh_token_expires_at TIMESTAMP WITH TIME ZONE,
    -- New employee fields
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    department VARCHAR(100) NOT NULL,
    position VARCHAR(100) NOT NULL,
    hiring_date DATE NOT NULL,
    salary DECIMAL(12, 2) NOT NULL CHECK(salary > 0)
);

-- Migrate data from app_users_legacy to employees
-- For existing users, fill required fields with defaults
INSERT INTO employees (
    id, username, password, role, active, created_at, updated_at,
    refresh_token, refresh_token_expires_at,
    first_name, last_name, email, phone, department, position, hiring_date, salary
)
SELECT
    id,
    username,
    password,
    CASE WHEN role = 'STAFF' THEN 'EMPLOYEE' ELSE role END,
    active,
    created_at,
    CURRENT_TIMESTAMP,
    refresh_token,
    refresh_token_expires_at,
    -- Cross-database defaults for legacy users
    'Employee',
    username,
    LOWER(username) || '@company.local',
    NULL,
    'General',
    'Staff',
    CAST(created_at AS DATE),
    1.00
FROM app_users
WHERE id IS NOT NULL;

-- Create indexes for performance
CREATE INDEX idx_employees_email ON employees(email);
CREATE INDEX idx_employees_phone ON employees(phone);
CREATE INDEX idx_employees_department ON employees(department);
CREATE INDEX idx_employees_position ON employees(position);
CREATE INDEX idx_employees_role ON employees(role);
CREATE INDEX idx_employees_active ON employees(active);
CREATE INDEX idx_employees_username ON employees(username);
CREATE INDEX idx_employees_created_at ON employees(created_at DESC);

-- app_users table is intentionally kept for backward compatibility with current auth flow.
