CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(32)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    phone      VARCHAR(64),
    email      VARCHAR(255),
    active     BOOLEAN      NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_customers_code UNIQUE (code)
);
