CREATE TABLE inventory_transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL,
    order_id   BIGINT,
    type       VARCHAR(8)  NOT NULL,
    quantity   INTEGER     NOT NULL,
    reason     VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inv_txn_product FOREIGN KEY (product_id) REFERENCES products     (id),
    CONSTRAINT fk_inv_txn_order   FOREIGN KEY (order_id)   REFERENCES sales_orders (id)
);
