CREATE TABLE payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number VARCHAR(64)    NOT NULL,
    order_id       BIGINT         NOT NULL,
    amount         DECIMAL(15, 2) NOT NULL,
    method         VARCHAR(16)    NOT NULL,
    note           VARCHAR(500),
    paid_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_payments_payment_number UNIQUE (payment_number),
    CONSTRAINT uk_payments_order_id       UNIQUE (order_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES sales_orders (id)
);

CREATE TABLE invoices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(64)    NOT NULL,
    order_id       BIGINT         NOT NULL,
    payment_id     BIGINT         NOT NULL,
    total_amount   DECIMAL(15, 2) NOT NULL,
    issued_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_invoices_invoice_number UNIQUE (invoice_number),
    CONSTRAINT uk_invoices_order_id       UNIQUE (order_id),
    CONSTRAINT uk_invoices_payment_id     UNIQUE (payment_id),
    CONSTRAINT fk_invoices_order   FOREIGN KEY (order_id)   REFERENCES sales_orders (id),
    CONSTRAINT fk_invoices_payment FOREIGN KEY (payment_id) REFERENCES payments    (id)
);
