CREATE TABLE sales_returns (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_number VARCHAR(64)    NOT NULL,
    order_id      BIGINT         NOT NULL,
    reason        VARCHAR(500)   NOT NULL,
    status        VARCHAR(16)    NOT NULL,
    total_refund  DECIMAL(15, 2) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_sales_returns_return_number UNIQUE (return_number),
    CONSTRAINT uk_sales_returns_order_id      UNIQUE (order_id),
    CONSTRAINT fk_sales_returns_order FOREIGN KEY (order_id) REFERENCES sales_orders (id)
);

CREATE TABLE sales_return_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_return_id BIGINT        NOT NULL,
    order_item_id  BIGINT         NOT NULL,
    quantity       INTEGER        NOT NULL,
    unit_price     DECIMAL(15, 2) NOT NULL,
    line_total     DECIMAL(15, 2) NOT NULL,
    CONSTRAINT fk_return_items_return     FOREIGN KEY (sales_return_id) REFERENCES sales_returns (id),
    CONSTRAINT fk_return_items_order_item FOREIGN KEY (order_item_id)  REFERENCES order_items   (id)
);
