CREATE TABLE discounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(32)    NOT NULL,
    type                VARCHAR(8)     NOT NULL,
    discount_value      DECIMAL(15, 2) NOT NULL,
    min_order_amount    DECIMAL(15, 2),
    max_discount_amount DECIMAL(15, 2),
    active              BOOLEAN        NOT NULL DEFAULT TRUE,
    expires_at          TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_discounts_code UNIQUE (code)
);

ALTER TABLE sales_orders
    ADD COLUMN discount_id     BIGINT;

ALTER TABLE sales_orders
    ADD COLUMN discount_amount DECIMAL(15, 2);

ALTER TABLE sales_orders
    ADD CONSTRAINT fk_sales_orders_discount FOREIGN KEY (discount_id) REFERENCES discounts(id);
